### PR TITLE
Validation of C-TAEA

### PR DESCRIPTION
**Pull request by cyrilpic**
Going through the [C-code ](https://cola-laboratory.github.io/codes/CTAEA.zip), I found some differences with the algorithm in the paper and well as some bugs in the previous implementation.

One point that I needed to address is what is done in ASF when the weight as a value of zero. They use 1e-4, while you were using 10e-10 and it created some difference when sorting the solutions. I added an option to choose a different value in your ASF. This can be removed if you don't like it.

In order to ensure correctness, there are:
* some tests validating the selection steps (text files generated from the C code)
* a benchmark script for 3 functions (only for 3 objectives so far)

Running the C code I don't exactly get the same values as published in the paper, so I bundled the output of the algorithm here for you to compare:
[out.zip](https://github.com/msu-coinlab/pymoo/files/4678117/out.zip)

Let me know how I can further help.

### CODE REVIEW

**Comment by julesy89** [comment]
Excellent!  I have merged the new version into master. No worries, the values are usually not exactly the same. I had to realize the same when I have implemented NSGA3. 

I would like to extend the benchmark to the majority of the test problems in the paper. How much work would that be?

Finally, I shall ask K Li to have a final look and ask for permission to add his algorithm to pymoo. He has been visiting our lab (http://www.coin-lab.org) in the past (before I have joined the lab but anyway). I do not think there will be any issues if the performance is not significantly different.

**Comment by cyrilpic** [comment]
Sorry for the long delay.

I can run the original C code to generate the results for almost all test problems in the paper and send you the data. This should be doable fairly rapidly.
But most of the test problems are missing from pymoo: C3DTLZ1 and the DC-DTLZ test suite. C3DTLZ1 should be straightforward to implement and I can dig into DC-DTLZ.

**Comment by julesy89** [comment]
That sounds excellent. 
Yes, pymoo has a few cdtlz problems but not all of them. DC-DTLZ would be good to have too in general. I just would like to make sure the performance of the algorithm is the same as in the paper. Looking forward to your pull request when you found the time to implement it.

**Comment by julesy89** [comment]
I am currently planning what to include for the next pymoo release and I was wondering what your timeline for the benchmark for CTAEA is?

Thanks,
Julian

**Pull request merged**
