### PR TITLE
AGE MOEA implementation PR

### PR DESCRIPTION
**Pull request by BenCrulis**
Hello, I have written an implementation of the AGE-MOEA algorithm from 2019:
Panichella, A. (2019). An adaptive evolutionary algorithm based on non-euclidean geometry for many-objective optimization. GECCO 2019 - Proceedings of the 2019 Genetic and Evolutionary Computation Conference, July, 595–603.
https://doi.org/10.1145/3321707.3321839

The code is heavily inspired from the existing implementation of AGE-MOEA in the PlatEMO library (Matlab).

This algorithm does not require reference directions to function. It is based on the general framework of NSGA-II and works by estimating the shape of the Pareto front and then using this information to design a score that take into account both the performance and proximity of the solutions with their neighbors to select the best solutions.

It is currently not capable of handling constraints since in the original Matlab implementation the constraint handling is done at the Non-dominated sorting step and I did not find an equivalent option with the provided NDS implementation of pymoo.

This is my first pull request to a public repository so let me know if everything is in order.

### CODE REVIEW

**Comment by julesy89** [comment]
I have just had a look, and first, I would like to mention that your code looks pretty clean and is nicely organized! Great job!

Have you benchmark this implementation, and were you able to reproduce the results from the paper? Was the original source code in the PlatEMO framework submitted by the authors or already being reimplemented by someone else?

If we can ensure that the performance is similar, I would like to create a small documentation page (e.g., for NSGA-II see doc/algorithms/nsga2.ipynb) to demonstrate how to run the algorithm. Of course, your name as the one who has implemented it will be mentioned there too.

**Comment by BenCrulis** [comment]
> Was the original source code in the PlatEMO framework submitted by the authors or already being reimplemented by someone else?

The author of the paper leaved his name in the comments of some functions of the PlatEMO implementation so we can only assume he wrote the entire algorithm himself, or at least sent his source code to one of the maintainer of PlatEMO.

> were you able to reproduce the results from the paper?

I've ran some benchmarks on the problems that are implemented in pymoo (mainly the DTLZ suite) and it seems to often match or outperform MOEAD and NSGA-III.

Here are some results I got on 3-dimensional DTLZ2 after 50 generations for each algorithm:
```
Algo name: AGE-MOEA
repetition: 1
generations: 50
seed: 864039
execution time: 4.467249631881714
GD+: 0.05149810207419841
IGD+: 0.05116937053207928
solutions: 200
non dominated solutions: 200

Algo name: moead
repetition: 1
generations: 50
seed: 8154060
execution time: 6.8486340045928955
GD+: 0.09426337564724864
IGD+: 0.09589795924450702
solutions: 200
non dominated solutions: 155

Algo name: nsga-III
repetition: 1
generations: 50
seed: 4674378
execution time: 2.650967836380005
GD+: 0.050295546363454575
IGD+: 0.05626546812435614
solutions: 200
non dominated solutions: 163
```
I can attach a scatter plot of the solutions if you want, from what I can see it is quite uniformly distributed.

Unfortunately I couldn't test on the same problems as in the paper since this test suite is not implemented in pymoo
(The Maf test suite: Ran Cheng, Miqing Li, Ye Tian, Xingyi Zhang, Shengxiang Yang, Yaochu Jin,and Xin Yao. 2017.  A benchmark test suite for evolutionary many-objective optimization.Complex & Intelligent Systems3, 1 (01 Mar 2017), 67–81.  https://doi.org/10.1007/s40747-017-0039-7)

I just noticed that the cdist function from scipy does not accept a `p` parameter of value less than 1 and throws an error, I'll have to find a workaround because the algorithm crashes on ConvexDTLZ2 on some other problems because of that.
It is possible that there was a mistake in the original implementation and that the condition to set p to 1 should be:
```python
if np.isnan(p) or p <= 1.0:
    p = 1.0
```

The second thing is that in the current state, it doesn't handle constraints because they are supposed to be handled in the non-dominated sorting step. Should I implement a workaround or should I maybe update the NDS implementation to allow constraint handling?

When everything is resolved, I'll be glad to help writing the documentation page!

**Comment by BenCrulis** [comment]
After some investigation, it seems the issue with the parameter `p` is related to the version of scipy that is used. It works with `p < 1` in scipy version `1.5.1` but not in `1.6.1`.

A quick git blame in scipy repository indicate a change 8 months ago for the 1.6.0 release which introduced the exception: https://github.com/scipy/scipy/commit/e6ccf937a861bd5b8784f4906a468ce833e1a2f6

I'll just compute the minkowski "distance" manually to avoid this.

I don't understand why they introduced this change. The Matlab implementation of the equivalent function pdist2 perfectly allows `0 < p < 1`.

**Comment by julesy89** [comment]
Yes, manual computing the distance should not be that difficult.
Optimizing `ZDT4` caused an exception for me.

I have tried to fix it by:

```
    for i in range(m - np.sum(selected)):
        mg = np.meshgrid(np.arange(selected.shape[0])[selected], remaining)
        D_mg = distances[tuple(mg)]  # avoid Numpy's future deprecation of array special indexing

        if D_mg.shape[1] > 1:
            # equivalent to mink(distances(remaining, selected),neighbors,2); in Matlab
            maxim = np.argpartition(D_mg, neighbors - 1, axis=1)[:, :neighbors]
            tmp = np.sum(np.take_along_axis(D_mg, maxim, axis=1), axis=1)
            index: int = np.argmax(tmp)
            d = tmp[index]
        else:
            index = D_mg[:, 0].argmax()
            d = D_mg[index, 0]

        best = remaining.pop(index)
        selected[best] = True
        crowd_dist[best] = d
```

Would that fix be correct according to the original algorithm description?

**Comment by BenCrulis** [comment]
This is an issue with the function that finds extreme points it seems. The number of already selected points should always be at least 2 in 2 dimensions as the extreme points are already marked as selected at line 206. If the number of already selected points is greater than 2, D_mg should always have at least two columns and thus it should not fail at line 237.

From what I can see, the find_corner_solutions function returns duplicated indexes if a line and a column are full of zeros, which explains the issue. I will try to fix by forcing the function to return at least two different indexes instead.

**Comment by BenCrulis** [comment]
Let me know if it fixed it for you.

Now we should decide how I should handle the problem constraints.

**Comment by cyrilpic** [comment]
@BenCrulis : there is some constraint handling done by the parent class `Survival`, [see line 91](https://github.com/msu-coinlab/pymoo/blob/567901c0681081e7e928ccc51c0ec6c7a3e32edd/pymoo/model/survival.py#L91). Only feasible solutions are passed to AGE-MOEA's survival method. This maybe sufficient.

**Comment by BenCrulis** [comment]
@cyrilpic Good point, I just committed changes that will let the Survival superclass handle the constraints.
It seems to work correctly on a real world problem although the algorithms seems a bit less performant than its peers on this one.

**Comment by BenCrulis** [comment]
I've made a few changes to make AGE-MOEA more robust as there was a ground for crashes because of both scipy's cdist function and missing ranks in the population. Also AGE-MOEA now accepts and uses by default the same TournamentSelection as NSGA-II, which improves convergence speed a bit, as for NSGA-II.

I've also added documentation which currently looks much like NSGA-II's page. Let me know if you think I should add some figures or more explanations. I've  added a documentation link to NSGA-II since both algorithms are very similar.

I rebased on develop to hopefully make merging easier for you, I had to patch from my branch based on master since some files changed location.
Patching made some commits marked as authored by myself but written with my email address, I don't know how it happened. If you have the ability to remove the authoring or tell me how to do it, that would be great. It currently shows my email address in plain text which is not ideal.

Let me know if everything is in order.

**Comment by julesy89** [comment]
I have merged the version to the new release. Your contribution will be mentioned! Thank you!
If you have implementations of other algorithms, please let me know.

**Pull request closed without merging**
