### PR TITLE
Implement C-TAEA

### PR DESCRIPTION
**Pull request by cyrilpic**
This is an implementation of a two-archive many-objective optimization algorithm specifically designed for constrained problems.

This algorithm normally uses a "half" GA. So, only one of the offsprings from the crossover is kept. I adapted the SimulatedBinaryCrossover to be able to do both. I'm not sure this is the best approach.

### CODE REVIEW

**Comment by cyrilpic** [comment]
I'm also interested in implementing other constraint handling strategies for the other algorithms. It's currently not so easy in pymoo to change the strategy inside for example NSGA-III. Maybe you could share your thoughts on the architecture.

**Comment by julesy89** [comment]
After having merged now your other contributions its the algorithms turn ;)
I have already merged it to the current master branch, but to add it to the documentation and main page we have to follow some more steps:

Have you already done any benchmarking for your implementation? Were you able to reproduce the results presented in the paper?

**Comment by cyrilpic** [comment]
I benchmarked the implementation on four problems (C2-DTLZ2, TNK, OSY and MW14) and I got similar results for all four. One of them is also in the paper and the results match.

**Comment by julesy89** [comment]
Sorry I for my late answer. To make sure the implementation is correct I usually set up an experiment containing at least a few test problems mentioned in the paper. 
Also, usually we shall do statistical tests to ensure correctness.

Did you implement the algorithm based on existing source code or directly from the paper?

On GitHub you can find a folder called benchmark which already contains files for nsga2 and nsga3. Can you set one up for C-TAEA? I can do the evaluation on our server, but I need to know what test problems to verify and what results we expect.

**Comment by cyrilpic** [comment]
The implementation is based on the c code by the authors and the Matlab version of PlatEMO, but then I used your method to do the decomposition and the perpendicular distance calculation to the reference directions.

I will setup the benchmark and let you know.

**Pull request merged**
