### PR TITLE
Add "starmap" parallel execution method

### PR DESCRIPTION
**Pull request by JoshKarpel**
This PR adds a convenient way to do parallel execution when you already have a "starmapping callable" available to you. If this PR seems like a reasonable approach, I'd be happy to write up documentation as well.

My development example:

```python
import numpy as np
from pymoo.model.problem import Problem

import multiprocessing

class MyProblem(Problem):
    def __init__(self, **kwargs):
        super().__init__(n_var = 10, n_obj = 1, n_constr = 0, xl = -5, xu = 5,
                         **kwargs)

    def _evaluate(self, x, out, *args, **kwargs):
        out["F"] = (x ** 2).sum(axis = -1)

with multiprocessing.Pool() as pool:
    problem = MyProblem(elementwise_evaluation = True, parallelization = ('starmap', pool.starmap))
    r = np.random.RandomState(seed = 1)
    X = r.random((5, problem.n_var))
    result = problem.evaluate(X).squeeze()
expected = (X ** 2).sum(axis = -1)

print(result)
print(expected)

assert np.all(result == expected)
print('yay')
```

NB: to make this possible, because `_evaluate` is a method of the `Problem` and we need to pickle a `Problem` to send this to a multiprocessing pool, I needed to add a `__setstate__` method to `Problem` that sets the `parallelization` to `None` in any unpickled `Problem`:

```python
    def __getstate__(self):
        state = self.__dict__.copy()
        state["parallelization"] = None
        return state
```

I don't know much about how pymoo is used out in the wild, and this is certainly a breaking change, but it seems unlikely that anyone who was already using the "dask" parallelization method would have been shipping `Problem` via pickle (and it doesn't break `None` or "threads").

### CODE REVIEW

**Comment by julesy89** [comment]
Thanks for the contribution!

I have not used the parallelization features very much by myself (just for one project I have had it was necessary). If you have further improvements of our framework let me know.

**Comment by JoshKarpel** [comment]
Great! I'll move ahead with documentation.

**Comment by JoshKarpel** [comment]
@julesy89 Documentation pushed; I think this is ready for review.

**Comment by julesy89** [comment]
I am just merging the Documentation. And for me in my Jupyter Lab it actually works.

What is the error message in the Jupyter Notebook?

**Comment by JoshKarpel** [comment]
Oh! How odd. It works for me as well. Must have been an ephemeral error. I just pushed a new commit without the warning and with the cell executed.

**Comment by JoshKarpel** [comment]
@julesy89 I was checking in on this and it looks like you merged it manually. If so, should I go ahead and close the PR? Any other work you'd like me to do on it?

**Comment by julesy89** [comment]
Yes I had to. Github automatic merge showed me that there was a conflict and I should merge it manually. The modifications are included in the current master branch.

Thanks again for contributing!

You can close the PR.

**Comment by JoshKarpel** [comment]
My pleasure!

**Pull request closed without merging**
