### PR TITLE
Implemented 1+1 crossover and enables algorithms to repair a single individual

### PR DESCRIPTION
**Pull request by Peng-YM**

### CODE REVIEW

**Comment by julesy89** [comment]
Thanks for the pull request!

I just had a look and I think it should be generalized to work for any kind of crossover, since it is implemented in the `Crossover` class. So far, this assumes the crossover needs exactly two parents to create offsprings. But, for instance, the  `DifferentialEvolutionCrossover` needs three parents. In general, the cross method should be suitable for any arbitrary crossover which means it takes a list of individuals.

Can you generalize the code to be suitable for any kind of crossover? Also, can you create a two or three test cases that make sure that changes later on will not break the implementation?

Thank you in advance.

**Comment by Peng-YM** [comment]
Good suggestions, generalization ability is very important since it is a base class. I will take some time to implement it.

**Comment by Peng-YM** [comment]
Hi Julian, now the crossover can accept a list of individuals as its input. It will return all offspring as a population.
```python
problem = get_problem('zdt1')
sampling = get_sampling('real_random')
pop = sampling.do(problem, n_samples=3)

# two individuals as input
crossover = get_crossover('real_sbx', eta=20)
crossover.do(problem, pop[0], pop[1])
# population as input
crossover.do(problem, pop, np.array([[0, 1]]))

# three individuals as input
crossover = get_crossover('real_de')
crossover.do(problem, pop[0], pop[1], pop[2])
# population as input
crossover.do(problem, pop, np.array([[0, 1, 2]]))
```

**Comment by julesy89** [comment]
I think have a crossover just for a few individuals is a very good idea. I am about to release a new version and have implemented your suggestion in a slightly different way. 

```
problem = get_problem('zdt1')

sampling = FloatRandomSampling()

pop = sampling.do(problem, n_samples=3)

crossover = ElementwiseCrossover(SBX(20))
off = crossover.do(problem, pop[0], pop[1])
assert len(off) == 2

crossover = ElementwiseCrossover(DEX())
off = crossover.do(problem, pop[0], pop[1], pop[2])
assert len(off) == 1
```

This way the interface is not changed, but what you intend to do can be easily achieved. Let me know what you think.
(current release branch)

Julian

**Pull request closed without merging**
